apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inflection-ru.fullname" . }}-{{ .Values.languageCode }}
  labels:
    app: {{ include "inflection-ru.fullname" . }}
    language: {{ .Values.languageCode }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "inflection-ru.fullname" . }}
      language: {{ .Values.languageCode }}
  template:
    metadata:
      labels:
        app: {{ include "inflection-ru.fullname" . }}
        language: {{ .Values.languageCode }}
    spec:
      containers:
        - name: {{ include "inflection-ru.fullname" . }}-{{ .Values.languageCode }}
          image: "{{ .Values.image.repository }}:{{ $.Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 8000
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}