apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-db-util.fullname" . }}-exporter-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    databases:
      grammr:
        dsn: !env MONITORING_DSN