{{- range $.Values.languages }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "morphology.fullname" $ }}-{{ .code }}
  labels:
    app: {{ include "morphology.fullname" $ }}
    language: {{ .code }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "morphology.fullname" $ }}
      language: {{ .code }}
  template:
    metadata:
      labels:
        app: {{ include "morphology.fullname" $ }}
        language: {{ .code }}
    spec:
      containers:
        - name: {{ include "morphology.fullname" $ }}-{{ .code }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          ports:
            - containerPort: 8000
          env:
            - name: SPACY_MODEL
              value: {{ .model }}
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml $.Values.startupProbe | nindent 12 }}
{{- end }}