{{ range $.Values.languages }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "morphology.fullname" $ }}-{{ .code }}
  labels:
    {{- include "morphology.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ include "morphology.fullname" $ }}
    language: {{ .code }}
{{- end }}